# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import noblePrize_pb2 as noblePrize__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in noblePrize_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelPrizesServiceStub(object):
    """NobelPrizes service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLaureatesByCategoryAndYear = channel.unary_unary(
                '/nobelprizes.NobelPrizesService/GetLaureatesByCategoryAndYear',
                request_serializer=noblePrize__pb2.CategoryYearRequest.SerializeToString,
                response_deserializer=noblePrize__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.GetLaureatesByMotivationKeyword = channel.unary_unary(
                '/nobelprizes.NobelPrizesService/GetLaureatesByMotivationKeyword',
                request_serializer=noblePrize__pb2.KeywordRequest.SerializeToString,
                response_deserializer=noblePrize__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.GetLaureateInfoByName = channel.unary_unary(
                '/nobelprizes.NobelPrizesService/GetLaureateInfoByName',
                request_serializer=noblePrize__pb2.NameRequest.SerializeToString,
                response_deserializer=noblePrize__pb2.LaureateInfoResponse.FromString,
                _registered_method=True)


class NobelPrizesServiceServicer(object):
    """NobelPrizes service definition
    """

    def GetLaureatesByCategoryAndYear(self, request, context):
        """Service for Query 1: Total number of laureates in a category between years
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureatesByMotivationKeyword(self, request, context):
        """Service for Query 2: Total number of laureates with motivations containing a keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureateInfoByName(self, request, context):
        """Service for Query 3: Get laureate info by first and last name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelPrizesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLaureatesByCategoryAndYear': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureatesByCategoryAndYear,
                    request_deserializer=noblePrize__pb2.CategoryYearRequest.FromString,
                    response_serializer=noblePrize__pb2.LaureateCountResponse.SerializeToString,
            ),
            'GetLaureatesByMotivationKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureatesByMotivationKeyword,
                    request_deserializer=noblePrize__pb2.KeywordRequest.FromString,
                    response_serializer=noblePrize__pb2.LaureateCountResponse.SerializeToString,
            ),
            'GetLaureateInfoByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateInfoByName,
                    request_deserializer=noblePrize__pb2.NameRequest.FromString,
                    response_serializer=noblePrize__pb2.LaureateInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nobelprizes.NobelPrizesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nobelprizes.NobelPrizesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelPrizesService(object):
    """NobelPrizes service definition
    """

    @staticmethod
    def GetLaureatesByCategoryAndYear(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobelprizes.NobelPrizesService/GetLaureatesByCategoryAndYear',
            noblePrize__pb2.CategoryYearRequest.SerializeToString,
            noblePrize__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureatesByMotivationKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobelprizes.NobelPrizesService/GetLaureatesByMotivationKeyword',
            noblePrize__pb2.KeywordRequest.SerializeToString,
            noblePrize__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureateInfoByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobelprizes.NobelPrizesService/GetLaureateInfoByName',
            noblePrize__pb2.NameRequest.SerializeToString,
            noblePrize__pb2.LaureateInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
