# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: noblePrize.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'noblePrize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10noblePrize.proto\x12\x0bnobelprizes\x1a\x1bgoogle/protobuf/empty.proto\"M\n\x13\x43\x61tegoryYearRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nstart_year\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_year\x18\x03 \x01(\x05\"!\n\x0eKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"4\n\x0bNameRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"&\n\x15LaureateCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"J\n\x14LaureateInfoResponse\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nmotivation\x18\x03 \x01(\t2\xb5\x02\n\x12NobelPrizesService\x12\x65\n\x1dGetLaureatesByCategoryAndYear\x12 .nobelprizes.CategoryYearRequest\x1a\".nobelprizes.LaureateCountResponse\x12\x62\n\x1fGetLaureatesByMotivationKeyword\x12\x1b.nobelprizes.KeywordRequest\x1a\".nobelprizes.LaureateCountResponse\x12T\n\x15GetLaureateInfoByName\x12\x18.nobelprizes.NameRequest\x1a!.nobelprizes.LaureateInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'noblePrize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYYEARREQUEST']._serialized_start=62
  _globals['_CATEGORYYEARREQUEST']._serialized_end=139
  _globals['_KEYWORDREQUEST']._serialized_start=141
  _globals['_KEYWORDREQUEST']._serialized_end=174
  _globals['_NAMEREQUEST']._serialized_start=176
  _globals['_NAMEREQUEST']._serialized_end=228
  _globals['_LAUREATECOUNTRESPONSE']._serialized_start=230
  _globals['_LAUREATECOUNTRESPONSE']._serialized_end=268
  _globals['_LAUREATEINFORESPONSE']._serialized_start=270
  _globals['_LAUREATEINFORESPONSE']._serialized_end=344
  _globals['_NOBELPRIZESSERVICE']._serialized_start=347
  _globals['_NOBELPRIZESSERVICE']._serialized_end=656
# @@protoc_insertion_point(module_scope)
